language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tyzion/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tyzion/react-test npm test

after_success:
  - docker build -t tyzion/multi-client ./client
  - docker build -t tyzion/multi-nginx ./nginx
  - docker build -t tyzion/multi-server ./server
  - docker build -t tyzion/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to dockerHub
  - docker push tyzion/multi-client
  - docker push tyzion/multi-nginx
  - docker push tyzion/multi-server
  - docker push tyzion/multi-worker
